# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: 'webclient'
      verbose: false

  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      workingDir: 'webclient'
      command: custom
      verbose: false
      customCommand: 'run build'

  - task: CopyFiles@2
    displayName: 'Copy Files to Stageing Directory'
    inputs: 
     SourceFolder: '$(System.DefaultWorkingDirectory)/webclient/build'
     TargetFolder: '$(Build.ArtufactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
